In [96]:
import random 
import numpy as np 
import matplotlib.pyplot as plt
import nnfs
nnfs.init()

In [134]:
np.random.seed(1)
x = np.random.rand(100,1)  # x= example
print(X)
y = x*x
#print(y)

[[ 0.00000000e+00  0.00000000e+00]
 [ 2.99555692e-03  9.64660756e-03]
 [ 1.28809698e-02  1.55628482e-02]
 [ 2.99747903e-02  4.44809627e-03]
 [ 3.93124595e-02  9.32828337e-03]
 [ 8.28829070e-04  5.04982509e-02]
 [ 5.34835160e-02  2.85062827e-02]
 [ 4.17361967e-02  5.70752136e-02]
 [ 5.54633923e-02  5.87686822e-02]
 [ 8.16038325e-02  4.00659069e-02]
 [ 8.91875103e-02  4.74197045e-02]
 [ 1.07160836e-01 -2.93638241e-02]
 [ 1.21183202e-01 -2.64751446e-03]
 [ 1.28777727e-01  2.56794747e-02]
 [ 1.41112968e-01 -9.22449492e-03]
 [ 1.50579467e-01 -1.68126337e-02]
 [ 1.13476366e-01 -1.15077794e-01]
 [ 1.71552509e-01 -7.51816481e-03]
 [ 1.67186841e-01 -7.14591444e-02]
 [ 1.91325873e-01  1.50793232e-02]
 [ 1.36771902e-01  1.48679554e-01]
 [ 1.35606423e-01 -1.63114399e-01]
 [ 1.04024746e-01 -1.96370989e-01]
 [ 2.15633541e-01 -8.64653736e-02]
 [-9.83033329e-02 -2.21598670e-01]
 [ 2.46031418e-01 -5.68994507e-02]
 [ 1.24166250e-01 -2.31420174e-01]
 [ 1.32641941e-01 -2.38298729e-01]
 [-1.23804301e-01 -2

In [128]:
np.random.seed(2)

class Layer_Dense:     # network
    def __init__(self,lst=[]):
        self.weights = 0.10*np.random.randn(arr)  ## Total size of N_neuron
        self.biases = np.zeros((1,arr[1:-1]))  ## N_neuron in hidden layer
        def forward(self,x):
            self.output = np.dot(arr,self.weights) + self.biases
            return forward_op
        
class Activation_ReLU:
    def forward(self,arr):
        self.output = np.maximum(0,inputs)
    
    
layer1=Layer_Dense(arr,3)    

    

TypeError: Layer_Dense.__init__() takes from 1 to 2 positional arguments but 3 were given

In [145]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data


nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods




X, y = spiral_data(samples=100, classes=3)




dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate(activation2.output, y)

print("Loss:", loss)

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
Loss: 1.0986104


In [144]:
x = np.random.rand(100,1)  # x= example
print(x.shape)
y=x*x
print(y.shape)

(100, 1)
(100, 1)
